dataset_id: "Misleading-Prompt-Videos"
# model_id: "LLaVA-Video-7B-Qwen2"
# model_id: "mPLUG-Owl3-7B"
model_id: "InternVL2_5-78B"
# model_id: "MiniCPM-V-2_6"
# model_id: "long-llava-qwen2-7b"
# model_id : "VideoLLaMA3-7B"
# model_id: "Qwen-VL-MAX"
log_file: "./logs/robustness/robustness-misleading-prompt-Internvl2_5.json"


dataset_cfg: { 
  video_dir: './data/robustness/Misleading-Prompt-Videos/video',
  annotation_file: "./data/robustness/Misleading-Prompt-Videos/data.json",
  }


generation_kwargs: {
    'system': "Carefully watch the video and pay attention to the cause and sequence of events, the detail and movement of objects, and the action and pose of persons.\n",
    'max_new_tokens': 1024,
    'do_sample': False,
  }

evaluator_seq_cfgs:
  [

    {
      "chatmodel_eval":
        { 
          model_id: 'deepseek-chat',
          prompt_template: "Compare the semantic similarity between 'Pred' and 'Label' (expected output). Assess if their meanings align, answer me [Yes] or [No]: Pred: \n{pred}\n   Label: \n{label}\n",
          generation_kwargs: {
              'max_new_tokens': 128,
              'do_sample': False,
          },
          metrics_cfg: {}
        },
   
      "rule_yes_or_no_eval":
        { metrics_cfg: { pred_mean: {} }},
    }
  ]