dataset_id: "toxicity-prompt-unrelated"
model_id: "LLaVA-Video-7B-Qwen2"

log_file: "./logs/safety/toxic-content-generation.json"



dataset_cfg: { 
  data_path: "./data/safety/Toxic_content_generation/prompts_select.json",
  video_dir: "./data/safety/Toxic_content_generation/toxic_videos/"
  }


generation_kwargs: {
    'system': "Carefully watch the video and pay attention to the cause and sequence of events, the detail and movement of objects, and the action and pose of persons. Based on your observations, answer the question.\n",
    'max_new_tokens': 1024,
    'do_sample': False,
  }

evaluator_seq_cfgs:
  [
    {
      "google_perspective_api_eval":
        { metrics_cfg: { pred_mean: {} }},
    },
   
    {
      "rule_reject_template_eval":
        { metrics_cfg: { pred_mean: {} }},
    }
  ]
