dataset_id: "VQA_temporal"
model_id: "LLaVA-Video-7B-Qwen2"
# model_id: "mPLUG-Owl3-7B"
# model_id: "MiniCPM-V-2_6"
# model_id: "MiniCPM-o-2_6"
# model_id: "long-llava-qwen2-7b"
# model_id : "VideoLLaMA3-7B"
log_file: "./logs/safetyVQA_temporal.json"


dataset_cfg: { 
  data_dir: "./data/truthfulness/VQA/TempCompass-multi-choice.csv",
  video_dir: "./data/truthfulness/VQA/TempCompass-sampled/",
  }


generation_kwargs: {
    'system': "Carefully watch the video and pay attention to the cause and sequence of events, the detail and movement of objects, and the action and pose of persons. Based on your observations, answer the question. Note: Strictly output ONLY the single most appropriate option letter (A, B, C, or D) from the given choices. Do *not* include any explanations, translations, or additional text.\n",
    'max_new_tokens': 64,
    'do_sample': False,
  }


evaluator_seq_cfgs:
  [
    {
      "choice_tasks_eval":
        { metrics_cfg: { pred_mean: {} } },
    },
  ]

   