dataset_id: "CapERA"
model_id: "LLaVA-Video-7B-Qwen2"
# model_id: "MiniCPM-o-2_6"
log_file: "./logs/robustness/ood-video-CapERA.json"

generation_kwargs: {
    'system': "Carefully watch the video and pay attention to the cause and sequence of events, the detail and movement of objects, and the action and pose of persons.\n",
    'max_new_tokens': 64,
    'do_sample': False,
}

dataset_cfg: { 
  video_path: "./data/robustness/Capera_sampled/sampled_videos/",
  data_dir: "./data/robustness/Capera_sampled/ood_videos.json"
}

evaluator_seq_cfgs:
  [
    {
      "chatmodel_eval":
        { 
          model_id: 'deepseek-chat',
          prompt_template: "Your task is to compare a generated response with multiple references and determine if the generated response is semantically similar to any of them. Follow these steps and criteria: \nInput:\nGenerated Response: A single text string.\nReferences: Five text strings (Reference 1, Reference 2, Reference 3, Reference 4, Reference 5).\nJudgment Criteria:\nCheck the semantic similarity between the generated response and each reference individually (whether the meaning is consistent or close to any one of them).\nFocus on the semantic core, including theme, intent, and key information, ignoring minor wording differences. If the generated response is highly consistent with at least one of the references in terms of semantics, consider them similar.\nOutput:\nIf similar to at least one reference, output 'Yes'.\nIf not similar to any reference, output 'No'.\nNow, please judge based on the following input:\nGenerated Response: {pred}\nReferences:\nReference 1: {label1}\nReference 2: {label2}\nReference 3: {label3}\nReference 4: {label4}\nReference 5: {label5}\nOutput only 'Yes' or 'No' directly, without explaining a process.",
          generation_kwargs: {
                    'max_new_tokens': 20,
                    'do_sample': False,
                },
          metrics_cfg: {},
        },
    
      "rule_yes_or_no_eval":
        {
          metrics_cfg: { pred_mean: {} }
        },
    },
    {
      "bleu_meteor_cider_spice_eval":
      {
         metrics_cfg: { blue_rouge_meteor_cider_spice: {} },
      }
    }
  ]